# Generated by Django 3.1.4 on 2020-12-06 15:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_logo', models.ImageField(upload_to='module_logo')),
                ('module_number', models.IntegerField()),
                ('module_name', models.CharField(max_length=200)),
                ('status', models.CharField(default='Created', editable=False, max_length=200)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('module_description', models.TextField(default='description', max_length=200, null=True)),
                ('userid', models.CharField(blank=True, default=None, editable=False, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(default='Created', editable=False, max_length=200)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('userid', models.CharField(blank=True, default=None, editable=False, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('topic_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=200)),
                ('topic_number', models.IntegerField()),
                ('topic_description', models.TextField(max_length=400)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.module')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_number', models.IntegerField()),
                ('question', models.JSONField(blank=True, max_length=200, null=True)),
                ('question_type', models.IntegerField()),
                ('question_status', models.CharField(default='Created', editable=False, max_length=200)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.module')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.topics')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_number', models.IntegerField()),
                ('title_text', models.CharField(max_length=400)),
                ('title_intro', models.TextField(max_length=4400)),
                ('content_section', models.TextField(max_length=4400)),
                ('media_section', models.CharField(max_length=400)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.topics')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_string', models.JSONField(max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('userid', models.CharField(blank=True, default=None, editable=False, max_length=45)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.project')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.question')),
            ],
        ),
    ]
