# Generated by Django 3.0.8 on 2020-10-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(),
        ),
    ]
