# Generated by Django 3.0.8 on 2020-11-03 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_auto_20201019_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user_id',
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.User'),
        ),
    ]
