# Generated by Django 3.0.8 on 2020-11-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_auto_20201103_1444'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
