# Generated by Django 3.0.8 on 2020-11-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_auto_20201103_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='Created', editable=False, max_length=200),
        ),
    ]
