# Generated by Django 3.0.8 on 2020-11-03 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0008_auto_20201103_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created_by',
            new_name='user',
        ),
    ]
