# Generated by Django 3.0.8 on 2020-11-03 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0011_auto_20201103_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='time_answered',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
