# Generated by Django 3.0.8 on 2020-11-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0012_auto_20201103_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='created_by',
        ),
        migrations.AddField(
            model_name='answer',
            name='userid',
            field=models.CharField(blank=True, default=None, max_length=45),
        ),
    ]
