# Generated by Django 3.0.8 on 2020-11-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0013_auto_20201104_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='userid',
            field=models.CharField(blank=True, default=None, editable=False, max_length=45),
        ),
    ]
