# Generated by Django 3.0.8 on 2020-11-04 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0015_auto_20201104_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='project_id',
        ),
    ]
