# Generated by Django 3.0.8 on 2020-11-04 08:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0016_remove_answer_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='module_status',
        ),
        migrations.AddField(
            model_name='answer',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.Project'),
        ),
        migrations.AddField(
            model_name='module',
            name='status',
            field=models.CharField(default='Created', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='module',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='userid',
            field=models.CharField(blank=True, default=None, editable=False, max_length=45),
        ),
    ]
