# Generated by Django 3.0.8 on 2020-11-04 22:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0017_auto_20201104_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='module_logo'),
            preserve_default=False,
        ),
    ]
