# Generated by Django 3.0.8 on 2020-11-09 07:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0018_module_module_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_description',
            field=models.CharField(default='description', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('topic_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=200)),
                ('topic_number', models.IntegerField()),
                ('topic_description', models.CharField(max_length=400)),
                ('module_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.Module')),
            ],
        ),
    ]
