# Generated by Django 3.0.8 on 2020-11-09 14:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0019_auto_20201109_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTopics',
            fields=[
                ('subtopic_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subtopic_name', models.CharField(max_length=200)),
                ('subtopic_number', models.IntegerField()),
                ('subtopic_description', models.CharField(max_length=400)),
                ('topic_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.Topics')),
            ],
        ),
    ]
