# Generated by Django 3.0.8 on 2020-11-16 11:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0020_subtopics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_text', models.CharField(max_length=400)),
                ('title_intro', models.CharField(max_length=4400)),
                ('content_section', models.CharField(max_length=4400)),
                ('media_section', models.CharField(max_length=400)),
                ('subtopic_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.SubTopics')),
            ],
        ),
    ]
