# Generated by Django 3.0.8 on 2020-11-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0021_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_description',
            field=models.TextField(default='description', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
    ]
