# Generated by Django 3.0.8 on 2020-11-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0022_auto_20201116_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_string',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_section',
            field=models.TextField(max_length=4400),
        ),
        migrations.AlterField(
            model_name='content',
            name='title_intro',
            field=models.TextField(max_length=4400),
        ),
        migrations.AlterField(
            model_name='subtopics',
            name='subtopic_description',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topic_description',
            field=models.TextField(max_length=400),
        ),
    ]
