# Generated by Django 3.0.8 on 2020-11-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0023_auto_20201116_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_status',
            field=models.CharField(default='Created', editable=False, max_length=200),
        ),
    ]
