# Generated by Django 3.0.8 on 2020-11-16 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0024_auto_20201116_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='subtopic_id',
            new_name='subtopic',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='module_id',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='subtopics',
            old_name='topic_id',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='topics',
            old_name='module_id',
            new_name='module',
        ),
    ]
