# Generated by Django 3.1.3 on 2020-11-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0025_auto_20201116_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_string',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.JSONField(null=True),
        ),
    ]
