# Generated by Django 3.1.3 on 2020-11-17 14:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0026_auto_20201117_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_string',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
