# Generated by Django 3.1.3 on 2020-11-18 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0027_auto_20201118_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.content'),
        ),
    ]
