# Generated by Django 3.1.3 on 2020-11-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0029_auto_20201117_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_string',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
