# Generated by Django 3.1.3 on 2020-11-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0030_auto_20201123_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
