# Generated by Django 3.1.3 on 2020-12-01 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0032_auto_20201124_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='subtopic',
        ),
        migrations.RemoveField(
            model_name='question',
            name='subtopic',
        ),
        migrations.AddField(
            model_name='content',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.topics'),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.topics'),
        ),
        migrations.DeleteModel(
            name='SubTopics',
        ),
    ]
